
# first argument = number of points to generate
# second argument = dimension of each point
# third argument = output file
dna_data:
	python dna_generator.py 10 2 text.txt

# first argument = input dna data file
# second argument = k
seq_kmeans:
	python sequentialDNA_kmeans.py text.txt 5